name: Update Code

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:

  check-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint PHP Files
        run: |
          find . -type f -name "*.php" -print0 | xargs -0 -n1 php -l

  update-code:
    runs-on: ubuntu-latest
    environment: env
    env:
        subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
        app_service_name: ${{ vars.APP_SERVICE_NAME }}
        resource_group_name: ${{ vars.RESOURCE_GROUP_NAME }}

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure Subscription
        run: az account set --subscription ${{ env.subscription_id }}

      - name: Pull Latest
        run: az webapp deployment source sync --name ${{ env.app_service_name }} --resource-group ${{ env.resource_group_name }}